### ISSUE TITLE
About Trained Checkpoints and Licenses

### ISSUE THREAD

**Issue by PINTO0309** [AlvaroCavalcante/hand-face-detector#1]
Thank you for publishing this very interesting repository.

I have two questions.

1. I wanted to try your model right away and quickly tried to download the trained model, but the Google Drive link below does not seem to have assigned permissions for outside engineers to access it. Would it be possible to add a public setting to Google Drive?
  https://drive.google.com/drive/folders/1cKV8GuqBgVMhf_pAiWu-3zmuNdYcA7Dg?usp=sharing
  ![image](https://github.com/AlvaroCavalcante/hand-face-detector/assets/33194443/875ab3b4-02ed-4c0b-8ba0-31a1b9178210)

2. I enjoy optimizing and transforming all the useful machine learning models in the world for various frameworks. I enjoy presenting optimized models in my repository, and if possible I would like to optimize the model you have created and share it in my repository. If you are willing to share your saved_model, I would love to optimize it and share it with you, preferably with the license of your model. What is the license of this (`hand-face-detector`) repository?

- My hobby repo - PINTO_model_zoo - 419 Type
  https://github.com/PINTO0309/PINTO_model_zoo

**Comment by AlvaroCavalcante** [comment]
Hello @PINTO0309, I'm happy to hear about your interest in this project! I'll try to answer your questions here:

1 - Actually the link is correct. I didn't leave the models completely open just to have control of who is downloading and using the project, but you can request access and I will share it with you as soon as possible.

2 - Although I haven't added it yet in the repository, my intention is to adopt the Apache 2.0 license. That said, feel free to use the models in your own project. However, It would be nice if you could add a link to the original repository :)

If you have any other doubts, please, let me know and I'll do my best to help you.

**Comment by PINTO0309** [comment]
@AlvaroCavalcante 
Thank you for your prompt response.

1 - I immediately sent an access request from the following account. Your approval would be appreciated.
s00856kh@gmail.com

2 - Thank you! Of course I am going to refer you to the repository from which the quotes were taken. I have also committed to citation links and licenses for all 400+ other models. :+1:

**Comment by PINTO0309** [comment]
Thanks!
