### ISSUE TITLE
Does this dataset have the bounding boxes for the face and hands?

### ISSUE THREAD

**Issue by ramacha7** [AlvaroCavalcante/hand-face-detector#3]

**Comment by AlvaroCavalcante** [comment]
Hello @ramacha7, thank you for your interest in this work!

Yes, as described in the README.md file: "**The folder named "images" contains all the images and the labels in PASCAL VOC (xml) format. The "labels" folder, in contrast, contains the labels in ".txt" format for YOLO.**"

Please, let me know if you have any other doubt!
