### ISSUE TITLE
Question: I'm not sure where to find the code for implementing the YOLOv7 architecture.

### ISSUE THREAD

**Issue by yangfa-zhang** [AlvaroCavalcante/hand-face-detector#5]

**Comment by AlvaroCavalcante** [comment]
Hello @yangfa-zhang, how are you? The source code for the training of the YoloV7 model is not available yet in this repository. However, you can use the code of the official Yolo repository, using the txt annotations provided by this work! Let me know if I can help you with any other doubt.
